global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'observabilidade-api'
    metrics_path: /metrics
    static_configs:
      # "api" é o nome do serviço da aplicação dentro da rede do docker-compose
      - targets: ['api:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
